### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by lordmen99** [tintinscorpion/CarMarker-Animation#1]
Can u give example app please? then its can show speed too? so,we can to know example driver speed whem pickup passenger :+1:

**Comment by tintinscorpion** [comment]
Well I have made this library to show the animation of marker smoothly which many developers face problem when the marker has to turn along with the road turn. Ok I will create a repository where the whole code of pickup and destination and time remaining etc. will be present.
You can follow the steps section in the ReadMe.md file where i have explained how you can achieve the animation in demo.
Thanks for reviewing.

**Comment by tintinscorpion** [comment]
I have provided a demo how I have used the library . You can modify it if u like.

**Comment by lordmen99** [comment]
ok. thank you
