### ISSUE TITLE
Issue demo app

### ISSUE THREAD

**Issue by lordmen99** [tintinscorpion/CarMarker-Animation#2]
Hi, i have build demo app carmarker. when i type destination and start trip. carmarket not follow track have been draw before. :D. can fix it  please

**Comment by tintinscorpion** [comment]
Well car marker will follow route when u will press the fliatingaction button in red color

**Comment by tintinscorpion** [comment]
If your expectations are met please rate the library.

**Comment by lordmen99** [comment]
> Well car marker will follow route when u will press the floating button in red color.. A circle button pops out when the polyline is drawn.

not follow route drawn. i have test it. after setup pickup and destination then press red arrow, car marker just running in one line

**Comment by tintinscorpion** [comment]
Did u provide valid google map key?

**Comment by lordmen99** [comment]
> Did u provide valid google map key?

yes. sure

**Comment by tintinscorpion** [comment]
Ok i will test it

**Comment by tintinscorpion** [comment]
Another thing is check the library version used and if u can redownload the example app may work fine.. I checked the code and its working as shown in demo

**Comment by lordmen99** [comment]
on thing again, UI / app very lag or hard. maybe to many animation in UI

**Comment by tintinscorpion** [comment]
Yeah there are animations in everything so may be the lag was occuring and also depends on device. If you dont mind can you share your google map key so that I can test with that key the problem you are stating

**Comment by tintinscorpion** [comment]
Ok I got the issue what you were facing .. I have modified the file RouteActivity.java. Please copy the code from the repo and paste it in the downloaded file and you will get the animation. Hope I didnot trouble you much.

**Comment by lordmen99** [comment]
good. then about lag? this demo app very hardto run. i think to many animation library

**Comment by tintinscorpion** [comment]
Well i have provided my demo key of google map. you can check with that. If any problem occurs please attach screenshots with it.

**Comment by lordmen99** [comment]
and forgot, can u add notification when close reach destination before 1 Km send sound notification?

**Comment by tintinscorpion** [comment]
I can help you with that but that part is not related with this demo project. Provide me your email address where I will share you whats need to be done. Please rate the library and share it with your friends.

**Comment by lordmen99** [comment]
ok cool, this my email myfacefx@gmail.com

**Comment by tintinscorpion** [comment]
Ok I am closing this issue now. i will send u the code of how to recieve notification when the destination is 1 km away from the driver location.
