### ISSUE TITLE
If driver takes wrong route instead of suggested route, how to get new route and navigate the driver 

### ISSUE THREAD

**Issue by prabhusns33** [tintinscorpion/CarMarker-Animation#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by prabhusns33** [comment]
Hi Pritam Dasgupta, you work is great,
if the driver navigate out of the polyline or suggested route, he knows the shortcut , how we can re route him based on the location.. 

If we have multiple waypoints how to draw all in the polyline and create marker.

Thanks

**Comment by tintinscorpion** [comment]
**1.** Coming to the implementation part- You can take exact amount of Hashmap for how many suggested routes you have. Draw the polylines accordingly by  map.drawPolyline(extract latlng from hashmap);
Whenever the location is changed , check the latlng of that position and search it in the hashmap. If that latlng doesnot exist in hashmap , you have to rest call the google direction api service to get the route from that location to the destination for rerouting.
**2.** The feature request is an enhancement request for sound direction like "turn left " which is present in google native app.

**Comment by prabhusns33** [comment]
Thanks for the info Pritam Dasgupta,

The same i have tried to achieve, but i need to do calculation based on the distance, duration including the waypoints.  (Src -> waypoint 1 (7kms, 30mins) (10 rupees)  waypoint 1-> waypoint 2 (6km, 25min) (8rupees), waypoint2 -> destination (4km,10min) (6rupees) ) including price calcualtion.


here if driver takes alternate route, we need to check whether the current lat,lng is located in the poly line list using the following method,  
    **double tolerance = 50; // meters
  boolean isOnRoute = PolyUtil.isLocationOnPath(new LatLng(location.getLatitude(), location.getLongitude()), polyLineList, false, tolerance);

            if (isOnRoute) {
// is on the corrcet path
}else{
                // fetch new direction from google maps direction api

}**

Now new route with current lat lng included with src -> way point (new) -> old waypoints (optimize iss given as true) it will take waypoints in order)

how to acheive this.


so times mapsanimator is not drawing polyline properly

**Comment by tintinscorpion** [comment]
**For the distance calculation** - Google Direction Api provides you with the exact distance . Suppose if from travelling x to y is 24 km and if the driver follows the route then its basic calculation but now if driver from x location travels to x2 and then x3 and then to y, so what you will need to do is get the distance from x to x2 which will be present in direction api service and again x2 to x3 and then from x3 to y. Store all the distances value in list and when finally reached to y ,sum up the distances. So now you are getting total distance travelled. For time use the timer from when the journey starts and till the journey ends. Then you will get the exact time consumed. Now calculate the price according to your algorithm.
I will suggest when the driver takes a shortcut or something like waypoints then clear the previous drawn polyline and reroute it accordingly.

**Comment by prabhusnw** [comment]
> **For the distance calculation** - Google Direction Api provides you with the exact distance . Suppose if from travelling x to y is 24 km and if the driver follows the route then its basic calculation but now if driver from x location travels to x2 and then x3 and then to y, so what you will need to do is get the distance from x to x2 which will be present in direction api service and again x2 to x3 and then from x3 to y. Store all the distances value in list and when finally reached to y ,sum up the distances. So now you are getting total distance travelled. For time use the timer from when the journey starts and till the journey ends. Then you will get the exact time consumed. Now calculate the price according to your algorithm.
> I will suggest when the driver takes a shortcut or something like waypoints then clear the previous drawn polyline and reroute it accordingly.

Thanks Pritam Dasgupta,
